#
# Copyright (c) 2022 Contributors to the Eclipse Foundation
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License v. 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0,
# or the Eclipse Distribution License v. 1.0 which is available at
# http://www.eclipse.org/org/documents/edl-v10.php.
#
# SPDX-License-Identifier: EPL-2.0 OR BSD-3-Clause
#

name: Eclipse Grizzly NIO CI

on:
  pull_request:
  push:

jobs:
  build:
    name: Build Grizzly on JDK ${{ matrix.java_version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java_version: [ 21-ea ]

    steps:
    - name: Checkout for build
      uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: ${{ matrix.java_version }}
    - name: Maven Build
      run: |
        mvn --show-version \
            --no-transfer-progress \
            --activate-profiles staging \
            --define skipTests=true \
            install

  test:
    name: Test Grizzly on JDK ${{ matrix.java_version }}
    runs-on: ubuntu-latest
    needs: build

    strategy:
      matrix:
        java_version: [ 21-ea ]

    steps:
    - name: Checkout for build
      uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: ${{ matrix.java_version }}
    - name: Maven Build
      run: |
        mvn --show-version \
            --no-transfer-progress \
            --fail-at-end \
            --activate-profiles staging \
            --define maven.test.redirectTestOutputToFile=true \
            --define forkCount=1 \
            --define reuseForks=false \
            --define surefire.reportFormat=plain \
            --define surefire.rerunFailingTestsCount=5 \
            install


